base/urls.py
from django.urls import include, path, re_path

from .ajax import ComboUpdateView
from .views import Error403View, HomeView

app_name = 'base'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name='error_403'),
]

# URLs de peticiones AJAX
urlpatterns += [
    re_path(
        r'^ajax/combo-update/?$',
        ComboUpdateView.as_view(),
        name='combo_update'
    ),
]

person/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    PersonCreateView,
    PersonDeleteView,
    PersonListView,
    PersonUpdateView,
)

app_name = 'person'

urlpatterns = [
    path('list/', login_required(PersonListView.as_view()), name='list'),
    path('create/', login_required(PersonCreateView.as_view()), name='create'),
    path(
        'update/<int:pk>/',
        login_required(PersonUpdateView.as_view()),
        name='update'
    ),
    path(
        'delete/<int:pk>/',
        login_required(PersonDeleteView.as_view()),
        name='delete'
    ),
]

base/models.py
from django.db import models


class Country(models.Model):
    """!
    Clase que contiene los paises

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre del pais
    name = models.CharField(max_length=80)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del país
        """

        return self.name


class State(models.Model):
    """!
    Clase que contiene los estados

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre del Estado
    name = models.CharField(max_length=50)

    # Pais en donde esta ubicado el Estado
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del estado
        """

        return self.name


class Municipality(models.Model):
    """!
    Clase que contiene los municipios

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre del Municipio
    name = models.CharField(max_length=50)

    # Estado en donde se encuentra el Municipio
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del municipio
        """

        return self.name


class City(models.Model):
    """!
    Clase que contiene las ciudades

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre de la Ciudad
    name = models.CharField(max_length=50)

    # Estado en donde se encuentra ubicada la Ciudad
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre de la ciudad
        """

        return self.name


class Parish(models.Model):
    """!
    Clase que contiene las parroquias

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre de la Parroquia
    name = models.CharField(max_length=50)

    # Municipio en el que se encuentra ubicada la Parroquia
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre de la parroquia
        """

        return self.name

person/models.py
from base.models import Parish
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.utils.translation import gettext_lazy as _


class Person(models.Model):
    """!
    Clase que contiene las personas

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    # Nombre
    first_name = models.CharField('nombres', max_length=100)

    # Apellido
    last_name = models.CharField('apellidos', max_length=100)

    # Cédula de identidad
    identification_card = models.CharField(
        'cédula de identidad',
        max_length=9,
        validators=[
            validators.RegexValidator(
                r'^[VE][\d]{8}$',
                _('Introduzca un número de cédula válido. Solo se permiten\
                números y una longitud de 8 carácteres. Se agrega un 0 si la \
                longitud es de 7 carácteres.')
            ),
        ], unique=True
    )

    # Número telefónico
    phone = models.CharField(
        'teléfono',
        max_length=15,
        validators=[
            validators.RegexValidator(
                r'^\+\d{2}-\d{3}-\d{7}$',
                _('Número telefónico inválido. Solo se permiten números.')
            ),
        ]
    )

    # Correo electrónico
    email = models.CharField(
        'correo electrónico', max_length=100, help_text=('correo@correo.com')
    )

    # Dirección
    address = models.CharField('dirección', max_length=100)

    # Relación entre la persona y la parroquia
    parish = models.ForeignKey(
        Parish, on_delete=models.CASCADE, verbose_name='parroquia'
    )

    # Relación entre la persona y el usuario del sistema
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='usuario'
    )

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre, apellido y la
            cédula de identidad
        """

        return '%s %s, %s' % (
            self.first_name, self.last_name, self.identification_card
        )

    class Meta:
        """!
        Meta clase del modelo que establece algunas propiedades

        @author William Páez (paez.william8 at gmail.com)
        """

        verbose_name = _('Persona')
        verbose_name_plural = _('Personas')

person/views.py
from base.constant import CREATE_MESSAGE, DELETE_MESSAGE, UPDATE_MESSAGE
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import PersonForm
from .models import Person


class PersonListView(ListView):
    """!
    Clase que muestra la lista de personas

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    model = Person
    template_name = 'person/list.html'

    def get_queryset(self):
        """!
        Función que obtiene la lista de personas que están asociados al usuario

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return queryset <b>{object}</b> lista de personas asociadas al usuario
        """

        queryset = Person.objects.filter(user=self.request.user)
        return queryset


class PersonCreateView(SuccessMessageMixin, CreateView):
    """!
    Clase que permite a un usuario registrar personas

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    model = Person
    form_class = PersonForm
    template_name = 'person/create.html'
    success_url = reverse_lazy('person:list')
    success_message = CREATE_MESSAGE

    def form_valid(self, form):
        """!
        Función que valida si el formulario está correcto

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param form <b>{object}</b> Objeto que contiene el formulario
        @return super <b>{object}</b> Formulario validado
        """

        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.parish = form.cleaned_data['parish']
        self.object.save()
        return super(PersonCreateView, self).form_valid(form)


class PersonUpdateView(SuccessMessageMixin, UpdateView):
    """!
    Clase que permite a un usuario actualizar los datos de una persona

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    model = Person
    form_class = PersonForm
    template_name = 'person/create.html'
    success_url = reverse_lazy('person:list')
    success_message = UPDATE_MESSAGE

    def dispatch(self, request, *args, **kwargs):
        """!
        Función que valida si el usuario del sistema tiene permisos para entrar
            a esta vista

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene los datos de la
            petición
        @param *args <b>{tuple}</b> Tupla de valores, inicialmente vacia
        @param **kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        @return super <b>{object}</b> Entra a la vista de actualización de una
            persona, sino redirecciona hacia la vista de error de permisos
        """

        if Person.objects.filter(pk=self.kwargs['pk'], user=self.request.user):
            return super(PersonUpdateView, self).dispatch(
                request, *args, **kwargs
            )
        else:
            return redirect('base:error_403')

    def get_initial(self):
        """!
        Función que agrega valores predeterminados a los campos del formulario

        @author William Páez (paez.william8 at gmail.com)
        @param self <b>{object}</b> Objeto que instancia la clase
        @return initial_data <b>{object}</b> Valores predeterminado de los
            campos del formulario
        """

        initial_data = super(PersonUpdateView, self).get_initial()
        initial_data['state'] = self.object.parish.municipality.state
        initial_data['municipality'] = self.object.parish.municipality
        return initial_data


class PersonDeleteView(SuccessMessageMixin, DeleteView):
    """!
    Clase que permite a un usuario eliminar los datos de una persona

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>
        GNU Public License versión 2 (GPLv2)</a>
    """

    model = Person
    template_name = 'person/delete.html'
    success_url = reverse_lazy('person:list')
    success_message = DELETE_MESSAGE

    def dispatch(self, request, *args, **kwargs):
        """!
        Función que valida si el usuario del sistema tiene permisos para entrar
            a esta vista

        @author William Páez (wpaez at cenditel.gob.ve)
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene los datos de la
            petición
        @param *args <b>{tuple}</b> Tupla de valores, inicialmente vacia
        @param **kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        @return super <b>{object}</b> Entra a la vista de actualización de una
            persona, sino redirecciona hacia la vista de error de permisos
        """

        if Person.objects.filter(pk=self.kwargs['pk'], user=self.request.user):
            return super(PersonDeleteView, self).dispatch(
                request, *args, **kwargs
            )
        else:
            return redirect('base:error_403')

    def delete(self, request, *args, **kwargs):
        """!
        Función que retorna el mensaje de confirmación de la eliminación

        @author William Páez (wpaez at cenditel.gob.ve)
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene los datos de la
            petición
        @param *args <b>{tuple}</b> Tupla de valores, inicialmente vacia
        @param **kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        @return super <b>{object}</b> Objeto con el mensaje de confirmación
            de la eliminación
        """

        messages.success(self.request, self.success_message)
        return super(PersonDeleteView, self).delete(request, *args, **kwargs)

person/templates/person/create.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'person:list' %}">Personas</a>
  </li>
  <li class="breadcrumb-item active">Registrar</li>
{% endblock %}
{% block content %}
  <div class="card">
    <div class="card-header">
      {% if not form.instance.pk %}{% trans 'Registrar' %}{% else %}{% trans 'Actualizar' %}{% endif %}
    </div>
    <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
      {% csrf_token %}
      <div class="card-body">
        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.first_name.auto_id }}">
                {{ form.first_name.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.first_name }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.first_name.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.last_name.auto_id }}">
                {{ form.last_name.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.last_name }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.last_name.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.identification_card.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.identification_card.auto_id }}">
                {{ form.identification_card.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.identification_card }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.identification_card.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.phone.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.phone.auto_id }}">
                {{ form.phone.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.phone }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                <small class="form-text text-muted">
                  {{ form.phone.help_text }}
                </small>
                {% include 'base/form.errors.html' with form_errors=form.phone.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.email.auto_id }}">
                {{ form.email.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.email }}
                  <i class="fa fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.email.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.state.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.state.auto_id }}">
                {{ form.state.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.state }}
                  <i class="fa fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.state.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.municipality.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.municipality.auto_id }}">
                {{ form.municipality.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.municipality }}
                  <i class="fa fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.municipality.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.parish.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.parish.auto_id }}">
                {{ form.parish.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.parish }}
                  <i class="fa fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.parish.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.address.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.address.auto_id }}">
                {{ form.address.label }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.address }}
                  <i class="fa fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.address.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer small text-right">
        <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
        <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% if not form.instance.pk %}{% trans 'Registrar' %}{% else %}{% trans 'Actualizar' %}{% endif %}</button>
      </div>
    </form>
  </div>
  <br>
{% endblock %}

{% block extra_footer %}
  <script type="text/javascript">
    $(document).ready(function() {
      if( $('#id_municipality').val() != '' && $('#id_parish').val() != '' )
      {
        $('#id_municipality').removeAttr('disabled');
        $('#id_parish').removeAttr('disabled');
      }
    });
  </script>
{% endblock %}

person/templates/person/delete.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'person:list' %}">Personas</a>
  </li>
  <li class="breadcrumb-item active">Eliminar</li>
{% endblock %}
{% block content %}
  <div class="card md-3">
    <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
      {% csrf_token %}
      <div class="card-header">Eliminar</div>
      <div class="card-body">
        <p>¿Estás seguro que deseas eliminar los datos de la Persona "{{ object }}"?</p>
      </div>
      <div class="card-footer small text-right">
        <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip">Eliminar</button>
      </div>
    </form>
  </div>
{% endblock %}

person/templates/person/list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item active">
    Personas
  </li>
{% endblock %}
{% block content %}
  <div class="card">
    <div class="card-header">
      Listar <a href="{% url 'person:create' %}" class="btn btn-success btn-sm float-right">Registrar</a>
    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered display dataTable" id="table" style="width:100%;">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Cédula</th>
              <th>Teléfono</th>
              <th>Correo</th>
              <th>Estado, Municipio, Parroquia</th>
              <th>Dirección</th>
              <th>Operación</th>
            </tr>
          </thead>
          <tbody>
            {% for person in object_list %}
              <tr>
                <td> {{ person.first_name }} </td>
                <td> {{ person.last_name }} </td>
                <td> {{ person.identification_card }} </td>
                <td> {{ person.phone }} </td>
                <td> {{ person.email }} </td>
                <td> {{ person.parish.municipality.state }}, {{ person.parish.municipality }}, {{ person.parish }} </td>
                <td> {{ person.address }} </td>
                <td> <a href="{% url 'person:update' person.id %}" title="Actualizar"><i class="far fa-edit" aria-hidden="true"></i></a> <a href="{% url 'person:delete' person.id %}" title="Eliminar"><i class="far fa-trash-alt" aria-hidden="true"></i></a> </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}
{% block extra_footer %}
  <script type="text/javascript">
    $(document).ready(function() {
      var table = $('#table').DataTable();
      button_datatable(table);
    });
  </script>
{% endblock %}